FROM node:16
WORKDIR /var/jenkins_home/workspace/deploy/release
COPY package*.json ./

# RUN yum install -y git-core curl build-essential openssl libssl-dev \
#  && git clone https://github.com/nodejs/node.git \
#  && cd node \
#  && ./configure \
#  && make \
#  && sudo make install
RUN npm install
COPY . .
RUN npm run build
EXPOSE 8081
CMD ['npm', 'start']
